#!/bin/bash

FILES="$@"
currentdir=${PWD##*/}
noaudio=""
count=1
for f in $FILES
do 
   if [ $count = 1 ]; then
     year=$1 
   elif [ $count = 2 ]; then
     genre=$2
   elif [ $count = 3 ]; then
     if [ $f = "-an" ]; then
       noaudio = "-an"
     else
       encodeList $f $currentdir- $year $genre $noaudio
     fi
   else
     encodeList $f $currentdir- $year $genre $noaudio
   fi
   count=`expr $count + 1`
done

