#!/bin/bash

ffmpeg -i $1 -c:v libx264 -profile:v main -level 3.1 -c:a aac -strict -2 -ab 128k -b:v 6800k -movflags faststart -vf "yadif=0:-1:0,scale=1920:1080" -metadata "genre="$2 -metadata "description=$2,$3" ${1%.*}-1080$4.mp4

