#!/bin/bash

###################
#   Encode video with specified frame rate.  Audio is disabled
# $1 - input file
# $2 - frame rate
# $3 - PTS mod factor (to double frame rate set to .5, etc.)
# $4 - genre
# $5 - filename extra

ffmpeg -r $2 -i $1 -c:v libx264 -profile:v main -level 3.1 -an -strict -2 -ab 128k -b:v 6800k -movflags faststart -vf "yadif=0:-1:0,setpts=$3*PTS" -metadata "genre="$4 ${1%.*}$5.mp4

