#!/bin/bash


inputFile=input.mp4
overlayFile1=overlay1.mp4
overlayFile2=overlay2.mp4
xPos1=50
yPos1=oh-ih-30
xPos2=ow-iw-50
yPos2=oh-ih-30
width=1920
height=1080
genre=timelapse
extra=overlay
alpha=0.8
blendmode=addition

PARAMS=""
while (( "$#" )); do
  case "$1" in
    -i|--input) 
        inputFile=$2
        shift 2
      ;;
    -o1|--overlay1)
        overlayFile1=$2 
        shift 2
      ;;
    -o2|--overlay2)
        overlayFile2=$2 
        shift 2
      ;;
    -bm|--blendmode)
        blendmode=$2 
        shift 2
      ;;
    -x1) 
        xPos1=$2
        shift 2
      ;;
    -y1) 
        yPos1=$2
        shift 2
      ;;
    -x2) 
        xPos2=$2
        shift 2
      ;;
    -y2) 
        yPos2=$2
        shift 2
      ;;
    -w) 
        width=$2
        shift 2
      ;;
    -h) 
        height=$2
        shift 2
      ;;
    -g) 
        genre=$2
        shift 2
      ;;
    -e) 
        extra=$2
        shift 2
      ;;
    -a) 
        alpha=$2
        shift 2
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done


# set positional arguments in their proper place
eval set -- "$PARAMS"

echo "inputFile= $inputFile"
echo "overlayFile1= $overlayFile1"
echo "overlayFile2= $overlayFile2"
echo "xPos1= $xPos1"
echo "yPos1= $yPos1"
echo "xPos2= $xPos2"
echo "yPos2= $yPos2"
echo "width= $width"
echo "height= $height"
echo "genre= $genre"
echo "extra= $extra"
echo "alpha= $alpha"
echo "blendmode= $blendmode"

#blend filter - first input is top layer, second input is bottom

ffmpeg -i $inputFile -i $overlayFile1 -i $overlayFile2 -filter_complex "[1:v] pad=$width:$height:$xPos1:$yPos1, setsar=sar=1, format=rgba [over1]; [2:v] pad=$width:$height:$xPos2:$yPos2, setsar=sar=1, format=rgba [over2]; [0:v] setsar=sar=1, format=rgba [bg]; [bg][over1] blend=all_mode=$blendmode:all_opacity=$alpha, format=rgba [combo1]; [combo1][over2] blend=all_mode=$blendmode:all_opacity=$alpha, format=yuva422p10le [comboall]; [comboall] format=yuv420p" -codec:a copy -metadata "genre="$genre ${inputFile%.*}$extra.mp4
